config/routes.rb
Foundry::Application.routes.draw do
  get "welcome/index"

  resources :flash_teams
 
  root 'welcome#index'

  resources :flash_teams do
    member do 
      get :get_status
      post :update_status
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :members
  has_many :subcategories
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  has_and_belongs_to_many :tasks
end

app/models/flash_team.rb
class FlashTeam < ActiveRecord::Base
  validates :name, presence: true

  has_many :tasks
  has_many :members
end

def get_all_flash_teams
  return FlashTeam.all
end

app/models/handoff.rb
class Handoff < ActiveRecord::Base
  has_and_belongs_to_many :tasks
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :flash_team
  belongs_to :category
  belongs_to :subcategory
  has_and_belongs_to_many :tasks
  has_and_belongs_to_many :skills
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_and_belongs_to_many :members
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  has_many :members
  belongs_to :category
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :flash_team
  has_and_belongs_to_many :members
  has_and_belongs_to_many :handoffs
  has_and_belongs_to_many :collaborations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flash_teams_controller.rb
require 'json'

class FlashTeamsController < ApplicationController
  helper_method :get_tasks

	def new
    @flash_team = FlashTeam.new
  end

  def create
    @flash_team = FlashTeam.new(flash_team_params)

    if @flash_team.save
      redirect_to @flash_team
    else
      render 'new'
    end
  end

  def show
    @flash_team = FlashTeam.find(params[:id])
  end

  def index
    @flash_teams = FlashTeam.all
  end

  def edit
    @flash_team = FlashTeam.find(params[:id])

    flash_teams = FlashTeam.all
    @events_array = []
    flash_teams.each do |flash_team|
      next if flash_team.json.blank?
      flash_team_json = JSON.parse(flash_team.json)
      flash_team_events = flash_team_json["events"]
      flash_team_events.each do |flash_team_event|
        @events_array << flash_team_event
      end
    end
    @events_json = @events_array.to_json
  end

  def update
    @flash_team = FlashTeam.find(params[:id])

    if @flash_team.update(flash_team_params)
      redirect_to @flash_team
    else
      render 'edit'
    end
  end

  def destroy
    @flash_team = FlashTeam.find(params[:id])
    @flash_team.destroy

    redirect_to flash_teams_path
  end

  def ajax_update
    @flash_team = FlashTeam.find(params[:id])
    @flash_team.json = 0
    @flash_team.save
  end

  def get_status
    @flash_team = FlashTeam.find(params[:id])
    respond_to do |format|
      format.json {render json: @flash_team.status, status: :ok}
    end
  end

  def update_status
    status = params[:localStatusJSON]
    @flash_team = FlashTeam.find(params[:id])
    @flash_team.status = status
    @flash_team.save

    respond_to do |format|
      format.json {render json: nil, status: :ok}
    end
  end

  def flash_team_params
    params.require(:flash_team).permit(:name, :json)
  end

  private :flash_team_params
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_teams_helper.rb
module FlashTeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/flash_teams/_form.html.erb
<%= form_for @flash_team do |f| %>
  <% if @flash_team.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@flash_team.errors.count, "error") %> prohibited
      this flash team from being created:</h2>
    <ul>
    <% @flash_team.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :json %><br>
    <%= f.text_area :json %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/flash_teams/edit.html.erb
<h1>Flash Teams/edit</h1>

<input id="authenticity_token" value="<%= form_authenticity_token %>" type="hidden"/>

<%= render 'form' %>

<%= tag :meta, :name=> 'events_json', :content=> @events_json %>

        <input type="hidden" id="flash_team_id" value="<%= @flash_team.id %>"/>
       <!--Main Layout-->
        <div class="container-fluid">       
            <div class="row-fluid">
                <!--<h1>Flash Teams</h1>-->
                <h1>Foundry</h1>
                    <div class="btn" id="flashTeamSaveBtn" onclick="saveFlashTeam" style="font-size:25px;">Save</div>
                    <div class="btn" id="flashTeamStartBtn" style="font-size:25px;">Start</div>
                    <div class="btn" id="flashTeamEndBtn" style="font-size:25px;">End</div>
					<div class="btn" id="addTimeBtn" onclick="addTime()" style="font-size:25px;">Add Time</div>
            </div>

            <div class="row-fluid">
                <div class="span3"> <!--Sidebar content-->
<!--                     <div id = "title-container" class="well">
							<form name="titleForm" id="title_form">
								<input type = "text" id="flashTeamTitle" placeholder="New Flash Team" style="font-size:25px; height:40px">
							</form>
						</div> 
-->	
                    <div id="member-container" class="well">
                        <h3>Team Roles</h3>
                        <form name='newMemberForm' autocomplete="on">
                            <div class="input-append">
                                <input class="span9" id="addMemberInput" type="text" placeholder="New Member" autocomplete="on">
                                <button class="btn" type="button" onclick="addMember()" id="addMemberButton">+Add</button>
                                <input type="submit" style="display:none">
                            </div>
                            <input type="text" name="enterAndReloadBugFix" style="display: none;"> 
                        </form>

                        <ul class = "nav nav-pills customPill" id="memberPills">
                            <!--Member Pills Appended Here in JS-->
                        </ul>
                    </div>
					
					<div id="search-events-container" class="well" style="overflow-y:scroll;">
					
					<!--<div class="btn btn-primary btn-large" id="promptbtn" style="margin:5px;">Prompt</div>
					
					<div id="dialog" title="Dialog Title">PROMPT</div>-->
					
						<div class="btn btn-primary btn-large" style="margin:5px;" onclick="addEvent()">Add Event</div>  
						<div class="input-append">
							<input class="span9" id="searchEventsInput" type="text" placeholder="Search...">
							<button class="btn" type="button" onclick="searchEvents()" id="searchEventsBtn">Go</button>
						</div>
						
						<div id="search-results"></div>
					</div>
					
					<div id="diagram-container" class="well">
                        <h3>Team Structure</h3>
                    </div>
					
                </div>

                <div class="span9"> <!--Body Content-->
                    
                    <div id="timeline-container" class="well" style="overflow-x:scroll; overflow-y:scroll;">
                        <h3>Project Workflow</h3>
                        <div class="overlay" id="overlay" onclick="overlayOff()" ondrop="drop(event)" ondragover="allowDrop(event)"> </div>

                    </div>
                </div>
            </div>
        </div>

        <%= javascript_include_tag "application" %>

<%= link_to 'Back', flash_teams_path %>

app/views/flash_teams/index.html.erb
<h1>Flash Teams Library</h1>
 
<%= link_to 'New Flash Team', new_flash_team_path %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody> 
  <% @flash_teams.each do |flash_team| %>
    <tr>
      <td><%= flash_team.id %></td>
      <!-- <td><%= flash_team.name %></td> -->
      <!-- <td><%= link_to 'Show', flash_team %></td> -->
      <td><%= link_to 'Edit', edit_flash_team_path(flash_team) %></td>
      <td><%= link_to 'Destroy', flash_team_path(flash_team), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/flash_teams/new.html.erb
<h1>Flash Teams/new</h1>

<%= render 'form' %>

<%= link_to 'Back', flash_teams_path %>

app/views/flash_teams/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @flash_team.name %>
</p>

<p>
  <strong>JSON:</strong>
  <%= @flash_team.json %>
</p>

<%= link_to 'Back', flash_teams_path %>
<%= link_to 'Edit', edit_flash_team_path(@flash_team) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foundry</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Foundry!</h1>
<%= link_to "Flash Teams Library", controller: "flash_teams" %>